#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("kyazoongaandroid.Resource", IsApplication=true)]

namespace kyazoongaandroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::kyazoongaRest.Resource.Drawable.monoandroidsplash = global::kyazoongaandroid.Resource.Drawable.monoandroidsplash;
			global::kyazoongaRest.Resource.String.library_name = global::kyazoongaandroid.Resource.String.library_name;
			global::kyazoongaRest.Resource.Style.Mono_Android_Theme_Splash = global::kyazoongaandroid.Resource.Style.Mono_Android_Theme_Splash;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int black = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int grey = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int lightgrey = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int listseparator = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int transparent = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int white = 2131099652;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int beach = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int calendar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int carticon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int cricketicon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cricketicong = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int custom_btn_orange = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int eventicon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int eventicong = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_launcher = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_tab_events = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_tab_my_cricket = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_tab_sports = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_tab_store = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_tab_theatre = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int kyazoongaogo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int launcher = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int loifl = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int monoandroidsplash = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int plants = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int seeds = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int shanghai = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int splash = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int splash_background = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int sportsicon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int sportsicong = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int storeicon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int storeiconw = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int theatreartsicon = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int theatreartsicong = 2130837533;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int Icon = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int Image = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int List = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int Text = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Text1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Text2 = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int Text3 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int Text5 = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int imageView1 = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int imageViewl = 2131165190;
			
			// aapt resource value: 0x7f070013
			public const int json_txt = 2131165203;
			
			// aapt resource value: 0x7f07000d
			public const int label = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int label1 = 2131165199;
			
			// aapt resource value: 0x7f070005
			public const int ll = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int login = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int myButton = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int password = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int separator = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int txt = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int username = 2131165198;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int back = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Clistview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int eventcat = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int events = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ImageAndSubtitleItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int imageandtexts = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Mains = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int splash = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Tab = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Splash = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int btnStyleOrange = 2131034114;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
